[package]
name = "bin-rp2040"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
defmt = "0.3.2"
defmt-rtt = "0.4.0"
libpoly = { path = "../libpoly" }
panic-probe = { version = "0.3.0", features = ["print-defmt"] }
rp2040-boot2 = "0.2.1"
rp2040-hal = "0.6.0"